### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by Majiko5121** [VulnTotal-Team/IoT-vulhub#12]
初始化环境（arm/mips/mipsel）
$ ./init_env.sh xxxx
请教大佬 这步要怎么执行啊 我在文件夹里没有找到这个脚本啊

**Comment by firmianay** [comment]
在每个漏洞环境的目录里

**Comment by Majiko5121** [comment]
感谢大佬 原来是有的漏洞文件夹里才有，还有一个问题请教您一下，就是我在自动化编译环境的时候提示：

# 自动化编译环境（目前通常有四种模拟方式）
$ docker-compose -f docker-compose-user.yml build         # QEMU 用户模式模拟
$ docker-compose -f docker-compose-system.yml build       # QEMU 系统模式模拟
$ docker-compose -f docker-compose-firmadyne.yml build    # firmadyne 模拟
$ docker-compose -f docker-compose-firmae.yml build       # firmae 模拟（方便调试）

报错信息：
Step 1/8 : FROM firmianay/qemu-system:mips
pull access denied for firmianay/qemu-system, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

其他的自动编译文件我也都试了一下 都是报这个错误，然后docker login显示我是登陆成功的，这个问题大佬知道是什么原因嘛

**Comment by firmianay** [comment]
因为没有上传dockerhub，要从头自己编译，可以看前几个issues

**Comment by Majiko5121** [comment]
这是一封来自qq邮箱的自动回复邮件。我已经收到您的邮件，我会尽快给您答复，请耐心等待。
