### ISSUE TITLE
等大佬指导，华为那个环境启动有问题

### ISSUE THREAD

**Issue by harry1080** [VulnTotal-Team/IoT-vulhub#17]
![image](https://user-images.githubusercontent.com/19358692/129001982-73f632aa-2cf4-44a1-b1e2-10535e71b0d6.png)

**Comment by harry1080** [comment]
> 大佬这截图我啥都看不出来。。。

大佬，能不能给一个联系方式，我方便截图给你

**Comment by yywz1999** [comment]
Wechat: pintool 你加我吧

**Comment by harry1080** [comment]
> > 大佬这截图我啥都看不出来。。。
> 
> 大佬，我将情况发邮件到你的邮箱[firmianay@gmail.com](mailto:firmianay@gmail.com)

大佬你的联系方式是多少？

**Comment by harry1080** [comment]
![image](https://user-images.githubusercontent.com/19358692/129653877-03a1d799-7480-4c36-bf7e-45ffc7178a0d.png)
![image](https://user-images.githubusercontent.com/19358692/129653948-45c8044e-e0a2-4af0-a683-ac256b54bcc7.png)
![image](https://user-images.githubusercontent.com/19358692/129654024-254971d0-b17d-48ae-8255-e2ed486b3ab2.png)
没法启动ssh转发

**Comment by harry1080** [comment]
已经完成漏洞复现，可以关闭这个提问了
