### ISSUE TITLE
docker构建成功，启动失败

### ISSUE THREAD

**Issue by K1p2y3** [VulnTotal-Team/IoT-vulhub#23]
![图片](https://user-images.githubusercontent.com/40665473/195291999-dd11315f-b795-4d23-981f-a84863907792.png)

**Comment by NchengN** [comment]
请问师傅这个问题解决了吗

**Comment by K1p2y3** [comment]
解决了，我把虚拟机回复快照了

**Comment by NchengN** [comment]
这个原因是不是创建的镜像问题

**Comment by K1p2y3** [comment]
可以试试把文件拷贝到images目录里，之后再启动
![图片](https://user-images.githubusercontent.com/40665473/195515866-3c5438d8-876a-47dc-895e-57c231d8c059.png)

**Comment by K1p2y3** [comment]
在armf里重新build，然后再启动试试

**Comment by NchengN** [comment]
我解决了师傅，麻烦了

**Comment by wsxk** [comment]
你好，请问这些文件应该从哪里下载，debian的网址里已经没有这3个文件了

**Comment by xiaofeng789** [comment]
俺也想问一下这些文件在哪里找

**Comment by xiaofeng789** [comment]
> 俺也想问一下这些文件在哪里找

我复现的漏洞是VIVOTEK/remote_stack_overflow/
我所需要的是firmianay/qemu-system              armel 
我的下载地址：
https://file.erlkonig.tech/debian-armel/debian_wheezy_armel_standard.qcow2
https://file.erlkonig.tech/debian-armel/initrd.img-3.2.0-4-versatile
https://file.erlkonig.tech/debian-armel/vmlinuz-3.2.0-4-versatile

https://file.erlkonig.tech/debian-armel/debian_squeeze_armel_standard.qcow2
https://file.erlkonig.tech/debian-armel/initrd.img-2.6.32-5-versatile
https://file.erlkonig.tech/debian-armel/vmlinuz-2.6.32-5-versatile
