### ISSUE TITLE
$ docker run --rm -v $PWD/firmware/:/root/firmware firmianay/binwalk -Mer "/root/firmware/DIR822A1_FW103WWb03.bin"

### ISSUE THREAD

**Issue by zhjygit** [VulnTotal-Team/IoT-vulhub#30]
dlink实验中，这里的“$ docker run --rm -v $PWD/firmware/:/root/firmware firmianay/binwalk -Mer "/root/firmware/DIR822A1_FW103WWb03.bin"”是有问题的吧。
执行run.sh的时候，通过extractor.py提取固件，这里通过docker run xxx/binwalk预先提取了固件，感觉重复了吧。

**Comment by firmianay** [comment]
可以跳过这一步，firmadyne本身带固件提取的功能
